/**
 * Embed the vision-tower WGSL sources into a generated TS module so the
 * browser bundle and the Bun/Dawn test harness import the exact same strings
 * (mirrors scripts/build-lfm2-artifact.ts: shader files are the source of
 * truth, the generated module is committed).
 *
 *   bun run scripts/build-vision-shaders.ts
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const shaderDir = resolve(here, "../src/vision/shaders");
const output = resolve(here, "../src/vision/shaders.generated.ts");

const names = [
  "patch_embed",
  "layernorm",
  "matmul",
  "gelu_tanh",
  "attention",
  "residual_add",
  "unshuffle_project",
] as const;

const sources = Object.fromEntries(
  await Promise.all(
    names.map(async (name) => [
      name,
      await readFile(resolve(shaderDir, `${name}.wgsl`), "utf8"),
    ] as const),
  ),
);

await writeFile(
  output,
  "// THIS FILE IS AUTO-GENERATED - DO NOT EDIT\n"
    + "// Generated by scripts/build-vision-shaders.ts.\n\n"
    + `export const visionShaders = ${JSON.stringify(sources)} as const;\n`,
);

console.log(`[webgpu] embedded ${names.length} vision shaders -> ${output}`);
