import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  defineLfm2,
  LFM2_INCLUDE_NAMES,
  LFM2_SHADER_NAMES,
  type Lfm2IncludeName,
  type Lfm2ShaderName,
} from "../src/lfm2-definition";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const shaderDir = resolve(root, "src/shaders");
const includeDir = resolve(shaderDir, "includes");
const output = resolve(root, "src/lfm2.artifact.generated.ts");

async function readNamed<K extends string>(
  dir: string,
  names: readonly K[],
): Promise<Record<K, string>> {
  return Object.fromEntries(
    await Promise.all(
      names.map(async (name) => [
        name,
        await readFile(resolve(dir, `${name}.wgsl`), "utf8"),
      ] as const),
    ),
  ) as Record<K, string>;
}

const sources = await readNamed<Lfm2ShaderName>(shaderDir, LFM2_SHADER_NAMES);
const includes = await readNamed<Lfm2IncludeName>(includeDir, LFM2_INCLUDE_NAMES);
const definition = defineLfm2({ sources, includes });
const artifact = definition.engine.serialize(definition.engine.link());

await writeFile(
  output,
  `// THIS FILE IS AUTO-GENERATED - DO NOT EDIT\n// Generated by scripts/build-lfm2-artifact.ts via Sandblaster.serialize().\n\nexport const lfm2Artifact = ${JSON.stringify(artifact)} as const;\n`,
);

console.log(`[webgpu] serialized LFM2 artifact: ${artifact.length} bytes -> ${output}`);
