import { artifactReport } from "@sandblaster/core";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  defineLfm2,
  LFM2_INCLUDE_NAMES,
  LFM2_SHADER_NAMES,
  TRAINING_SHADER_NAMES,
  KRYSTAL_FORWARD_SHADER_NAMES,
  KRYSTAL_BACKWARD_SHADER_NAMES,
  type Lfm2IncludeName,
  type Lfm2ShaderName,
  type TrainingShaderName,
  type KrystalForwardShaderName,
  type KrystalBackwardShaderName,
} from "../src/lfm2-definition";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const shaderDir = resolve(root, "src/shaders");
const includeDir = resolve(shaderDir, "includes");
const trainingDir = resolve(shaderDir, "training");
const output = resolve(root, "src/lfm2.artifact.generated.ts");
const reportOutput = resolve(root, "lfm2.report.html");

async function readNamed<K extends string>(
  dir: string,
  names: readonly K[],
): Promise<Record<K, string>> {
  return Object.fromEntries(
    await Promise.all(
      names.map(async (name) => [
        name,
        await readFile(resolve(dir, `${name}.wgsl`), "utf8"),
      ] as const),
    ),
  ) as Record<K, string>;
}

const core = await readNamed<Lfm2ShaderName>(shaderDir, LFM2_SHADER_NAMES);
const training = await readNamed<TrainingShaderName>(trainingDir, TRAINING_SHADER_NAMES);
const krystal = await readNamed<KrystalForwardShaderName>(trainingDir, KRYSTAL_FORWARD_SHADER_NAMES);
const backward = await readNamed<KrystalBackwardShaderName>(trainingDir, KRYSTAL_BACKWARD_SHADER_NAMES);
const sources = { ...core, ...training, ...krystal, ...backward };
const includes = await readNamed<Lfm2IncludeName>(includeDir, LFM2_INCLUDE_NAMES);
const definition = defineLfm2({ sources, includes });
const artifact = definition.engine.serialize(definition.engine.link());

await writeFile(
  output,
  `// THIS FILE IS AUTO-GENERATED - DO NOT EDIT\n// Generated by scripts/build-lfm2-artifact.ts via Sandblaster.serialize().\n\nexport const lfm2Artifact = ${JSON.stringify(artifact)} as const;\n`,
);

console.log(`[webgpu] serialized LFM2 artifact: ${artifact.length} bytes -> ${output}`);

// The artifact is the only place the shaders and binding manifests exist in
// their *linked* form — lfm2-definition.ts is the input, not the result. Emit
// the readable view of that result alongside it, so the two can never be out of
// step with each other. Generated, not committed.
const report = artifactReport(artifact, {
  title: "Chomato · LFM2 artifact",
  generatedAt: new Date().toISOString(),
});
await writeFile(reportOutput, report);

console.log(`[webgpu] artifact report: ${(report.length / 1024).toFixed(1)} KiB -> ${reportOutput}`);
