import fs from "node:fs";
import path from "node:path";
import { fromModule, SchemaAnalyzer } from "@schema-pop/core";
import { exportPlan, tsCodec, tsExports, wgsl } from "@schema-pop/exporter";
import { schema } from ".";

const HEADER = `// THIS FILE IS AUTO-GENERATED BY src/schema/cli.ts\n// DO NOT EDIT THIS FILE MANUALLY!\n\n`;
const ENGINE_PATH = "../engine";

const save = (filePath: string, content: any, noHeader: boolean = false) => {
  const fullPath = path.join(ENGINE_PATH, filePath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(fullPath, (noHeader ? "" : HEADER) + String(content));
  console.log("🐑 wrote", fullPath);
};

console.log("🐑 Building schema ...");

const analyzer = new SchemaAnalyzer();

const cfg = {
  schemaName: "gpu",
  layout: "std430",
  autoSort: true,
  autoPack: false,
} as const;

const assertSchema = (schema: any) => {
  if (schema.errors?.length) {
    console.error("Schema errors:", schema.errors);
    process.exit(1);
  }
};
const popSchema = fromModule(schema).schema;
save("dist/pop.json", JSON.stringify(popSchema, null, 2));
const result = analyzer.analyze(popSchema, cfg);
assertSchema(result);
const schemaIR = result.plan;

const paths = {
  codec: "src/util/codec.ts",
  buffers: "src/util/buffers.ts",
  metadata: "src/util/metadata.ts",
  wgslCodec: "src/shaders/includes/codec.wgsl",
  wgslSchema: "src/shaders/includes/schema.wgsl",
  wgslBindings: "src/shaders/includes/bindings.wgsl",
  html: "schema.html",
};
const schemaContent =
  `import { $ } from "../../../schema/src/schema";\n\n` +
  tsExports({}).generate(schemaIR);

save("dist/schema.json", JSON.stringify(schemaIR, null, 2));
save(
  paths.codec,
  schemaContent + tsCodec({ importPath: "./schema", generatePatches: true }).generate(schemaIR),
);

save(paths.wgslSchema, wgsl({ outputStyle: "types" }).generate(schemaIR));
save(paths.wgslCodec, wgsl({ outputStyle: "helpers" }).generate(schemaIR));
save(paths.html, exportPlan(schemaIR, "html", {}), true);

console.log("🐏 Schema build complete.");
