const t0 = Date.now();
const log = (msg: string) => console.log(`[${((Date.now()-t0)/1000).toFixed(1)}s] ${msg}`);
log("importing createDawnGeneration");
const { createDawnGeneration } = await import("./src/exe/dawn-backend.ts");
log("imported");
const gen = await createDawnGeneration("/home/kr/Projects/chomato-monorepo/models/LFM2.5-1.2B-Instruct-WQ4.wq4");
log("backend ready");
const result = await gen.generate([1, 42, 43], 4);
log("tokens: " + JSON.stringify(result.tokens));
log("DONE");
