#!/usr/bin/env bash
# Full LoRA SFT run on the GPU-token dataset.
#
# Trains LFM2.5-1.2B-Instruct to emit <|reserved_100|> / <|reserved_101|> as GPU
# command delimiters (dataset generated by src/generate_gpu_token_dataset.ts).
#
#   * LoRA on attention/MLP  +  the two delimiter embedding rows (grad-masked)
#   * trains ONLY assistant turns (system/user masked out)
#   * saves reserved rows + roles.json and the PEFT LoRA adapter under out/
#   * reports validation metrics on gpu-token-dataset/validation.jsonl
#
# Run from anywhere in the repo:  bash packages/finetune/run_gpu_tokens.sh
set -euo pipefail
cd "$(dirname "$0")"

# Keep checked-in/generated data from going stale relative to the generator.
deno run --allow-write src/generate_gpu_token_dataset.ts

uv run python python/train_reserved_tokens.py \
  --model ../../models/safetensors \
  --data gpu-token-dataset/train.jsonl \
  --eval gpu-token-dataset/validation.jsonl \
  --roles roles/gpu-tokens.json \
  --out out/gpu-tokens \
  --steps 600 \
  --batch 4 \
  --seq-len 512 \
  --lr 2e-4 \
  --lora \
  --lora-r 16
